name: animated_widgets
description: Easily add animations on your screen with AnimatedWidgets. Add always your animated widgets in your component's tree, then activate them when you want to activate the animations.
version: 1.0.6
authors: [
  Florent Champigny <champigny.florent@gmail.com>
]
homepage: https://github.com/florent37/AnimatedWidgets

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  vector_math: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: